# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'dogeai-envoy'
primary_region = 'bos'

[processes]
web = "/etc/envoy/run_envoy.sh"

[build]
dockerfile = "./Dockerfile"

# Main HTTP service for Envoy - exposes internal port 8080 to ports 80/443
[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ["web"]

[[http_service.checks]]
grace_period = "30s"
interval = "30s"
method = "GET"
timeout = "10s"
path = "/health"

# VM configuration
[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
processes = ["web"]
