# fly.toml app configuration file generated for crawler-dawn-meadow-191 on 2025-03-05T12:57:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crawler-dawn-meadow-191'
primary_region = 'dfw'

[build]
  dockerfile = "./Dockerfile"
 
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
